### ISSUE TITLE
Build a 2.x archetype rather than on old (1.x) Archetype

### ISSUE THREAD

**Issue by sewe** [spotbugs/spotbugs-archetype#6]
At the moment, the build issues the following warning:

    Building an Old (1.x) Archetype: consider migrating it to current 2.x Archetype.

We should investigate why we get this warning and then make the switch to the 2.x archetype format. (Note that I don’t think we get this warning accidentally, as part of bug [ARCHETYPE-483](https://issues.apache.org/jira/browse/ARCHETYPE-483); we use a version of the `maven-archetype-plugin` where this bug is fixed already.)

**Comment by KengoTODA** [comment]
Closed by #7
