### ISSUE TITLE
mvn archetype:generate  error

### ISSUE THREAD

**Issue by 0kk4cce1er** [spotbugs/spotbugs-archetype#72]
mvn archetype:generate \
    -DarchetypeArtifactId=spotbugs-archetype \
    -DarchetypeGroupId=com.github.spotbugs \
    -DarchetypeVersion=0.2.3

[ERROR] [ERROR] Some problems were encountered while processing the 
[ERROR] Unresolveable build extension: Plugin org.sonatype.plugins:nexus-staging-maven-plugin:1.6.8 or one of its dependencies could not be resolved: Failed to collect dependencies at org.sonatype.plugins:nexus-staging-maven-plugin:jar:1.6.8 -> org.sonatype.nexus:nexus-client-core:jar:2.14.3-02 @ 
[ERROR] Unknown packaging: maven-archetype @ line 8, column 14
 @ 
[ERROR] The build could not read 1 project -> [Help 1]
[ERROR]   
[ERROR]   The project com.github.spotbugs:spotbugs-archetype:0.2.3-SNAPSHOT (/xxxxxxx/myfindbug/spotbugs-archetype/pom.xml) has 2 errors
[ERROR]     Unresolveable build extension: Plugin org.sonatype.plugins:nexus-staging-maven-plugin:1.6.8 or one of its dependencies could not be resolved: Failed to collect dependencies at org.sonatype.plugins:nexus-staging-maven-plugin:jar:1.6.8 -> org.sonatype.nexus:nexus-client-core:jar:2.14.3-02: Failed to read artifact descriptor for org.sonatype.nexus:nexus-client-core:jar:2.14.3-02: Could not transfer artifact org.sonatype.nexus.buildsupport:nexus-buildsupport-commons:pom:2.14.3-02 from/to rso-public-grid (https://repository.sonatype.org/content/groups/sonatype-public-grid/): Remote host closed connection during handshake: SSL peer shut down incorrectly -> [Help 2]
[ERROR]     Unknown packaging: maven-archetype @ line 8, column 14
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/ProjectBuildingException
[ERROR] [Help 2] http://cwiki.apache.org/confluence/display/MAVEN/PluginManagerException

i need help!!!

**Comment by KengoTODA** [comment]
> Could not transfer artifact org.sonatype.nexus.buildsupport:nexus-buildsupport-commons:pom:2.14.3-02 from/to rso-public-grid (https://repository.sonatype.org/content/groups/sonatype-public-grid/): Remote host closed connection during handshake: SSL peer shut down incorrectly

This is not problem of this project. 
If you can reproduce this problem, report to the admin of this repository.
